### ISSUE TITLE
Add JavaScript Concepts

### ISSUE THREAD

**Issue by shruti49** [shruti49/Hacktoberfest2021_beginners#1]

**Comment by realNameHidden1** [comment]
Hey I've added a concept of Set #23 , check my PR.

**Comment by harshvardhan614** [comment]
Hi @shruti49 mam, I added a event listener concept . kindly Review my PR #70 . Thank you.

**Comment by shruti49** [comment]
> hey, I have added a concept called regular expression, will that be counted as a valid contribution or should i try something else

Regular Expressions are general . you should go with concepts.

**Comment by shruti49** [comment]
> can I add more concepts @shruti49

yes you can add unique concepts or add more examples in the already concept file.

**Comment by amanag25** [comment]
@shruti49 mam please respond on this #71

**Comment by DurveshKumarPal** [comment]
@shruti49 class multiple constructors PR #147

**Comment by DurveshKumarPal** [comment]
@shruti49 (Function pass by reference and value) #148

**Comment by SohanaShabnam05** [comment]
Can I contribute on this project??

**Comment by Abhay5855** [comment]
Can I contribute to this issue , you can assign it to me

**Comment by shruti49** [comment]
I don't know whether your contribution will be counted or not.

**Comment by dhanashrisonawane28** [comment]
Do check PR #192 Hoisting concept added.

**Comment by dhanashrisonawane28** [comment]
Do check PR #193 JavaScript Closures code added.
