### ISSUE TITLE
Create a Beginner Level Project Section Based on the Javascript Concepts   

### ISSUE THREAD

**Issue by sumedhx** [shruti49/Hacktoberfest2021_beginners#112]
😇Hello,
I have Suggestions to Create a Javascript Project Section for Beginners to provide a better understanding of Javascript Concepts
This Section will contain Basic Project Based on the concepts like addEventListener(), Math.floor(), arrays, etc.

@shruti49 @swapnil0709 @ionlizarazu @Reayz @S-a-k-s-h-i #112

**Comment by shruti49** [comment]
> 😇Hello, I have Suggestions to Create a Javascript Project Section for Beginners to provide a better understanding of Javascript Concepts This Section will contain Basic Project Based on the concepts like addEventListener(), Math.floor(), arrays, etc.
> 
> @shruti49 @swapnil0709 @ionlizarazu @Reayz @S-a-k-s-h-i

Yeah we can do that.
